### ISSUE TITLE
nonce reuse

### ISSUE THREAD

**Issue by mafintosh** [little-core-labs/xsalsa20-encoding#1]
I think you are reusing the nonce when encoding multiple values which can lead to security issues.

A solution would be to generate a new nonce everytime and return it as part of the encoded payload.

**Comment by jwerle** [comment]
addressed in https://github.com/jwerle/xsalsa20-encoding/commit/8c286420f47d0846b5910e2ef8e21c504a521d32

**Comment by mafintosh** [comment]
Awesome!
